// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUobHw-zphmbnqYZuHaqaGzLGFF_Xlqr0',
    appId: '1:43317420718:android:75a3bb4b9c1c427ade433f',
    messagingSenderId: '43317420718',
    projectId: 'spotbuy-fafdc',
    storageBucket: 'spotbuy-fafdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEVufNAtdMTmpDDr2IH3DbkbtZzpI8-I',
    appId: '1:43317420718:ios:38818bb4a6188ed0de433f',
    messagingSenderId: '43317420718',
    projectId: 'spotbuy-fafdc',
    storageBucket: 'spotbuy-fafdc.appspot.com',
    androidClientId: '43317420718-8329sboa16v0a74vhudi77nea74v1ndu.apps.googleusercontent.com',
    iosClientId: '43317420718-h7a2irare327hcpmeotlavtjdo2ncr9a.apps.googleusercontent.com',
    iosBundleId: 'com.spotmobility.spotbuy',
  );
}
